### ISSUE TITLE
generated :hover classes seems odd

### ISSUE THREAD

**Issue by flpwgr** [kripod/otion#10]
## Description

Whenever I add a `:hover` to a class the output of it its something like this:

```
._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n:hover{border-color:blue}
```

## Reproduction

Here you can see it happening:
https://codesandbox.io/s/hoverissue-9386o?file=/src/App.tsx

## Expected behavior

the generated output should be smaller
```
._z4lg8n:hover { border-color: blue; }
```

## Actual behavior

```
._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n._z4lg8n:hover{border-color:blue}
```

**Comment by kripod** [comment]
Thank you for reporting!

This is not a bug, but a feature™. Currently, the specificity of properties and pseudo selectors is [controlled through class repetition](https://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/). This is required to avoid issues with atomicity, e.g. `padding-top` should take precedence over `padding`, even when only defined later.

Issue #1 is about improving this behavior. Until then, don’t worry about the length of generated selectors, as gzip and Brotli compression handles repetition without substantial overhead in production.

**Comment by flpwgr** [comment]
Oh Cool! :) Thanks for the clarification

**Comment by kripod** [comment]
Version 0.4.0 addresses this issue by [managing precedences without class name repetition](https://github.com/kripod/otion/commit/16acfbce0a12c36eff0cb1ece392c4699955846a). Please give it a try and get back to me if you notice any issues 😊
