### ISSUE TITLE
Otion SSR proposal to hide internal complexity

### ISSUE THREAD

**Issue by katywings** [kripod/otion#18]
## Motivation

- Trying to separate otion internal ssr logic from consumer business logic.

## Proposed implementation

```
import { setup } from "otion";
import {
  filterOutUnusedRules,
  getStyleTag,
  VirtualInjector,
} from "otion/server";

export const otion = function (func: Function, otionOptions = {}) {
  const injector = VirtualInjector();

  setup({ ...otionOptions, injector });

  let html = func();
  const styleTag = getStyleTag(filterOutUnusedRules(injector, html));
  html = html.replace("</head>", styleTag + "</head>");

  return html;
};
```

## Consumer usage
```js
import { otion } from 'otion/ssr'
const html = otion(() => {
  return someComplicatedConsumerSsrHtml();
})
```

## Details

- Earlier proposal https://twitter.com/Katy_Wings/status/1275193727275982849 ;)
- Example code: https://github.com/sossejs/sosse/blob/69806e8c5e83637ccf4005cef994c802a82402bc/otion/lib/main.ts#L8

Let me know if you have any questions :D

**Comment by kripod** [comment]
Thank you very much for suggesting this! It would significantly lower the barrier for consumers. I'll try my best to implement this during the weekend.

**Comment by katywings** [comment]
@kripod You're welcome ;), no stress and take care ^.^!

**Comment by kripod** [comment]
While this seems to be an interesting take, after a second thought, I lean towards a more transparent approach where each step is self-describing. As seen [in the Next.js example](https://github.com/kripod/otion/blob/fb5ef3c24d2371767503ddfeddaebbd2c3f5a5c2/packages/example-nextjs/pages/_document.tsx#L15-L22), otion shall be set up with a `VirtualInjector` _before_ rendering the HTML asynchronously, and afterwards, styles can be replaced with the solution provided by Next.js. A similar API exists in [Gatsby](https://github.com/kripod/otion/blob/fb5ef3c24d2371767503ddfeddaebbd2c3f5a5c2/packages/gatsby-plugin-otion/gatsby-ssr.js#L32-L34), which speaks for the preference of composability over conciseness.

Thanks for your ongoing efforts regarding this project and I apologize for being so late with the review.

**Comment by katywings** [comment]
My proposal wasnt meant as a replacement of the current api, but as an additional alternative ;). But I understand your points and having only one way for doing something can be an advantage 👍
