### ISSUE TITLE
Improve docs of @supports on CSSGroupingRules

### ISSUE THREAD

**Issue by etc-tiago** [kripod/otion#20]
I'm trying to correct the issue #19 through a pull request and the following block that code caught my attention:

```ts
export interface CSSGroupingRules<
  P extends Record<string, any> = CSSProperties
> {
  '@media'?: {
    [conditionText: string]: CSSRules<P>;
  };
  '@supports'?: {
    [conditionText: string]: CSSRules<P>;
  };
}
```
source: *src/cssTypes.ts*

What does `@supports` do? I couldn't find it anywhere else in the code.

**Comment by TxHawks** [comment]
[`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) is a css [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule), which, much like `@media`, is nestable. It is used for built-in feature detection

**Comment by etc-tiago** [comment]
@TxHawks Thanks for clarification
