### ISSUE TITLE
Docs suggestions

### ISSUE THREAD

**Issue by jaredpalmer** [kripod/otion#21]
- Add package installation instructions (`npm install xxx` etc) in the root README and in `otion` and in `react-otion` 
- Add CRA example
- Add codesandbox examples for (CRA, gatsby, next.js) to readme 
- Add codesandbox CI for PRs playgrounds https://codesandbox.io/docs/ci

**Comment by kripod** [comment]
Thank you for the very valuable feedback! I've been busy recently and had to cope with some stuff, but I'll try my best to make these changes soon.

**Comment by kripod** [comment]
Sandboxes are now available [from PRs](https://github.com/kripod/otion/pull/36#issuecomment-660621154) and [the readme](https://github.com/kripod/otion/tree/56a11341a962d44afac413f074537b755e4c52e2#getting-started), along with all the missing installation instructions.

Thankfully to @etc-tiago, a CRA example is now also avaliable. (However, it seems that TypeScript running within the CRA sandbox [fails to find the `otion` module's entry point](https://github.com/codesandbox/codesandbox-client/issues/4576).)

I appreciate all these suggestions and hope they will simplify the adoption for everyone.
