### ISSUE TITLE
Pseudo selector styles are applied directly

### ISSUE THREAD

**Issue by efflam** [kripod/otion#5]
## Description

Pseudo selector styles are applied directly

## Reproduction

https://codesandbox.io/s/nostalgic-yalow-yuwrg?file=/src/App.js

## Expected behavior

The div should be green and red on hover.

## Actual behavior

The div is red.

## Environment
Chrome Version 81.0.4044.138

**Comment by kripod** [comment]
Thank you for reporting! I'll also investigate why Code Sandbox cannot load otion as a package.

**Comment by kripod** [comment]
After further investigation, it turns out that Code Sandbox doesn't support loading modules with a `.cjs` extension. I've just fixed your use-case as shown here: https://codesandbox.io/s/fervent-grass-gbu2p?file=/src/App.js

**Comment by kripod** [comment]
@all-contributors Please add @efflam for reporting a bug!

**Comment by kripod** [comment]
@all-contributors Please add @efflam for bug reporting!

**Comment by kripod** [comment]
@all-contributors please add @efflam for bug

**Comment by kripod** [comment]
@all-contributors please add @efflam for reporting a bug!

**Comment by efflam** [comment]
Great ! Thank you
