### ISSUE TITLE
[Question] Otion is ready for use in production?

### ISSUE THREAD

**Issue by etc-tiago** [kripod/otion#50]
Since otion follows the semantic version, and has not yet released version 1.0.0, do you believe that otion is ready for use in production?

Otion proved to be an alternative to @emotion and styled components and I believe that the atomicity of css will be a trend for the future.  I would like to contribute more actively to the project and I would like to know if you have a roadmap for version 1.0.0...

**Comment by kripod** [comment]
Thank you for the question! The main barrier for v1 is thorough automatic testing. However, existing functionality should be safe to use. A section about this will be written to the monorepo's readme.

I would appreciate if you could help with writing tests, mainly for the `css()` function. You may find usage methods in the [otion package's readme](https://github.com/kripod/otion/blob/21fa39116a9cb76474fdeff93779301683bb4c92/packages/otion/README.md) and the [Gatsby example project](https://github.com/kripod/otion/blob/21fa39116a9cb76474fdeff93779301683bb4c92/packages/example-gatsby/src/pages/index.tsx). I recommend inspecting a [`VirtualInjector`](https://github.com/kripod/otion/tree/21fa39116a9cb76474fdeff93779301683bb4c92/packages/otion#server-side-rendering) to ensure that rules are generated properly.
