### ISSUE TITLE
Write full queries as top-level rules

### ISSUE THREAD

**Issue by souporserious** [kripod/otion#56]
## Motivation

It would be nice to be able to specify queries at the top-level. From what I can tell, this is currently not supported and they must always start with a conditional group and rules nested inside that.

```js
css({ '@media screen and (min-width: 480px)': { color: 'tomato' } })
```

This would make transitioning from another library like Emotion or Styled Components easier since they support this syntax.

**Comment by kripod** [comment]
Thank you for the idea! While this is very possible from a technical perspective, it would break static type checking for CSS properties. I’m closing this for now.

Please feel free to fork the project and experiment with it on your own, as I’m too busy to maintain it right now. Also, I started transitioning from CSS-in-JS to Tailwind’s utility classes and they are very convenient to use with no runtime at all. Dynamism is also possible by leveraging CSS custom properties and inline styles.
